# Generated by Django 3.1.3 on 2022-01-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='id',
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=80, primary_key=True, serialize=False, unique=True),
        ),
    ]
