# Generated by Django 3.1.3 on 2022-01-24 21:18

from django.db import migrations, models
import user.validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=220)),
                ('phone_number', models.CharField(max_length=10, validators=[user.validator.validatePhoneNo])),
            ],
        ),
    ]
