# Generated by Django 3.1.3 on 2022-01-26 21:51

from django.db import migrations, models
import user.validator


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=10, unique=b'I01\n', validators=[user.validator.validatePhoneNo]),
        ),
    ]
