# Generated by Django 3.1.3 on 2022-01-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInteraction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readevent',
            name='countReads',
            field=models.IntegerField(blank=True),
        ),
    ]
