# Generated by Django 3.1.3 on 2022-01-25 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userInteraction', '0002_auto_20220125_1331'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserId',
            new_name='User',
        ),
    ]
